platform :macos, '10.12’
target 'Electsys Utility' do
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'CrossroadRegex'
  pod 'Kanna', '~> 4.0.0'
  pod 'Alamofire'
  pod 'Alamofire-SwiftyJSON'
  pod "PromiseKit/Foundation", "~> 6.0"
  pod "PromiseKit", "~> 6.8"
  pod 'Path.swift', '~> 0.13'
  
end
