platform :macos, '10.12’
target 'Electsys Utility' do
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'CrossroadRegex'
  pod 'Kanna', '~> 4.0.0'
  pod 'Alamofire'
  pod 'Alamofire-SwiftyJSON'
  pod 'Version'
  pod 'CSV.swift', '~> 2.4.2'
end
